### ISSUE TITLE
4.05 support

### ISSUE THREAD

**Issue by copy** [issuu/ocaml-zmq#39]
On a clean 4.05.0+beta1 opam switch, trying to install zmq.3.2-2 I'm getting the error log below. On 4.04 it works fine, so I will assume it isn't a problem with my environment.

```
/home/copy/.opam/4.05.0+beta1+flambda/bin/ocamlopt.opt unix.cmxa -I /home/copy/.opam/4.05.0+beta1+flambda/lib/ocamlbuild /home/copy/.opam/4.05.0+beta1+flambda/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/copy/.opam/4.05.0+beta1+flambda/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
/home/copy/.opam/4.05.0+beta1+flambda/bin/ocamlfind ocamlc -g -ccopt -Wall -ccopt -W -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
+ /home/copy/.opam/4.05.0+beta1+flambda/bin/ocamlfind ocamlc -g -ccopt -Wall -ccopt -W -ccopt -Wextra -ccopt -O2 -c src/caml_zmq_stubs.c
In file included from src/caml_zmq_stubs.c:37:0:
src/uint64.h:15:29: error: unknown type name ‘uint64’
 value caml_uint_copy_uint64(uint64 i);
                             ^~~~~~
src/caml_zmq_stubs.c: In function ‘caml_zmq_set_uint64_option’:
src/caml_zmq_stubs.c:137:5: error: unknown type name ‘uint64’
     uint64 val = CAML_UINT_Uint64_val(socket_option);
     ^~~~~~
In file included from src/caml_zmq_stubs.c:37:0:
src/uint64.h:13:37: error: ‘uint64’ undeclared (first use in this function)
 #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
                                     ^
src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
     uint64 val = CAML_UINT_Uint64_val(socket_option);
                  ^~~~~~~~~~~~~~~~~~~~
src/uint64.h:13:37: note: each undeclared identifier is reported only once for each function it appears in
 #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
                                     ^
src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
     uint64 val = CAML_UINT_Uint64_val(socket_option);
                  ^~~~~~~~~~~~~~~~~~~~
src/uint64.h:13:45: error: expected expression before ‘)’ token
 #define CAML_UINT_Uint64_val(v) (*((uint64 *)Data_custom_val(v)))
                                             ^
src/caml_zmq_stubs.c:137:18: note: in expansion of macro ‘CAML_UINT_Uint64_val’
     uint64 val = CAML_UINT_Uint64_val(socket_option);
                  ^~~~~~~~~~~~~~~~~~~~
src/caml_zmq_stubs.c: In function ‘caml_zmq_set_int64_option’:
src/caml_zmq_stubs.c:154:5: error: unknown type name ‘int64’
     int64 val = Int64_val(Field(socket_option, 1));
     ^~~~~
src/caml_zmq_stubs.c: In function ‘caml_zmq_get_uint64_option’:
src/caml_zmq_stubs.c:237:5: error: unknown type name ‘uint64’
     uint64 mark;
     ^~~~~~
In file included from src/caml_zmq_stubs.c:15:0:
src/caml_zmq_stubs.c:244:17: warning: implicit declaration of function ‘caml_uint_copy_uint64’ [-Wimplicit-function-declaration]
     CAMLreturn (caml_uint_copy_uint64(mark));
                 ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:340:29: note: in definition of macro ‘CAMLreturnT’
   type caml__temp_result = (result); \
                             ^~~~~~
src/caml_zmq_stubs.c:244:5: note: in expansion of macro ‘CAMLreturn’
     CAMLreturn (caml_uint_copy_uint64(mark));
     ^~~~~~~~~~
src/caml_zmq_stubs.c: In function ‘caml_zmq_get_int64_option’:
src/caml_zmq_stubs.c:249:5: error: unknown type name ‘int64’
     int64 mark;
     ^~~~~
src/caml_zmq_stubs.c: In function ‘caml_zmq_event_recv’:
src/caml_zmq_stubs.c:496:5: error: unknown type name ‘zmq_event_t’
     zmq_event_t event;
     ^~~~~~~~~~~
src/caml_zmq_stubs.c:499:18: error: request for member ‘event’ in something not a structure or union
     switch (event.event) {
                  ^
In file included from src/caml_zmq_stubs.c:15:0:
src/caml_zmq_stubs.c:502:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.connected.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:503:44: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_fd(event.data.connected.fd));
                                            ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
 #  define Val_fd(x) Val_int(x)
                     ^~~~~~~
src/caml_zmq_stubs.c:503:32: note: in expansion of macro ‘Val_fd’
         Store_field(result, 1, Val_fd(event.data.connected.fd));
                                ^~~~~~
src/caml_zmq_stubs.c:507:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.connect_delayed.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:508:45: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_int(event.data.connect_delayed.err));
                                             ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:508:32: note: in expansion of macro ‘Val_int’
         Store_field(result, 1, Val_int(event.data.connect_delayed.err));
                                ^~~~~~~
src/caml_zmq_stubs.c:509:67: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.connect_delayed.err)));
                                                                   ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:514:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.connect_retried.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:515:45: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_int(event.data.connect_retried.interval));
                                             ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:515:32: note: in expansion of macro ‘Val_int’
         Store_field(result, 1, Val_int(event.data.connect_retried.interval));
                                ^~~~~~~
src/caml_zmq_stubs.c:520:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.listening.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:521:44: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_fd(event.data.listening.fd));
                                            ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
 #  define Val_fd(x) Val_int(x)
                     ^~~~~~~
src/caml_zmq_stubs.c:521:32: note: in expansion of macro ‘Val_fd’
         Store_field(result, 1, Val_fd(event.data.listening.fd));
                                ^~~~~~
src/caml_zmq_stubs.c:526:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.bind_failed.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:527:45: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_int(event.data.bind_failed.err));
                                             ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:527:32: note: in expansion of macro ‘Val_int’
         Store_field(result, 1, Val_int(event.data.bind_failed.err));
                                ^~~~~~~
src/caml_zmq_stubs.c:528:67: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.bind_failed.err)));
                                                                   ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:533:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.accepted.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:534:44: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_fd(event.data.accepted.fd));
                                            ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
 #  define Val_fd(x) Val_int(x)
                     ^~~~~~~
src/caml_zmq_stubs.c:534:32: note: in expansion of macro ‘Val_fd’
         Store_field(result, 1, Val_fd(event.data.accepted.fd));
                                ^~~~~~
src/caml_zmq_stubs.c:539:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.accept_failed.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:540:45: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_int(event.data.accept_failed.err));
                                             ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:540:32: note: in expansion of macro ‘Val_int’
         Store_field(result, 1, Val_int(event.data.accept_failed.err));
                                ^~~~~~~
src/caml_zmq_stubs.c:541:67: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.accept_failed.err)));
                                                                   ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:546:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.closed.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:547:44: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_fd(event.data.closed.fd));
                                            ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
 #  define Val_fd(x) Val_int(x)
                     ^~~~~~~
src/caml_zmq_stubs.c:547:32: note: in expansion of macro ‘Val_fd’
         Store_field(result, 1, Val_fd(event.data.closed.fd));
                                ^~~~~~
src/caml_zmq_stubs.c:552:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.close_failed.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:553:45: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_int(event.data.close_failed.err));
                                             ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:553:32: note: in expansion of macro ‘Val_int’
         Store_field(result, 1, Val_int(event.data.close_failed.err));
                                ^~~~~~~
src/caml_zmq_stubs.c:554:67: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 2, caml_copy_string(zmq_strerror(event.data.close_failed.err)));
                                                                   ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:559:54: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 0, caml_copy_string(event.data.disconnected.addr));
                                                      ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
src/caml_zmq_stubs.c:560:44: error: request for member ‘data’ in something not a structure or union
         Store_field(result, 1, Val_fd(event.data.disconnected.fd));
                                            ^
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/memory.h:353:27: note: in definition of macro ‘Store_field’
   value caml__temp_val = (val); \
                           ^~~
/home/copy/.opam/4.05.0+beta1+flambda/lib/ocaml/caml/mlvalues.h:77:20: note: in expansion of macro ‘Val_long’
 #define Val_int(x) Val_long(x)
                    ^~~~~~~~
src/caml_zmq_stubs.c:27:21: note: in expansion of macro ‘Val_int’
 #  define Val_fd(x) Val_int(x)
                     ^~~~~~~
src/caml_zmq_stubs.c:560:32: note: in expansion of macro ‘Val_fd’
         Store_field(result, 1, Val_fd(event.data.disconnected.fd));
                                ^~~~~~
Command exited with code 2.
```

**Comment by andersfugmann** [comment]
Latest version 4.0-7 builds fine with 4.05.0-beta3. Please reopen the issue if the problem is still present when using latest version of the code.

**Comment by copy** [comment]
@andersfugmann Indeed, the problem was that the latest version is marked as `available: [ ocaml-version < "4.05.0" ]`, so opam picked an older version (3.2-2) that didn't have this constraint.

**Comment by andersfugmann** [comment]
I see. 
I will update the opam package and remove the < "4.05.0" constraint from the latest package.

**Comment by andersfugmann** [comment]
PR created against opam package repository where the version constraint is removed: https://github.com/ocaml/opam-repository/pull/9015.
I also added a local opam file to allow pinning, so untill the PR is merged, then you can use:
```opam pin add zmq git://github.com/issuu/ocaml-zmq.git```

To compile agains the latest version for OCaml 4.05.0-betaX
